Shel:
  Neos:
    YoastSeo:
      devMode: false
      defaultContentLocale: en-US
      languageToLocaleMapping:
        da: 'da_DK'
        de: 'de_DE'
        en: ''
        es: 'es_ES'
        fi: 'fi'
        fr: 'fr_FR'
        km: ''
        lv: ''
        nl: 'nl_NL'
        no: 'nb_NO'
        pl: 'pl_PL'
        pt-BR: 'pt_BR'
        ru: 'ru_RU'
        zh-CN: 'zh_CN'
